# Generated by Django 5.2 on 2025-12-10 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование дня недели', max_length=31, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='SubjectsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование типа', max_length=127, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип предмета',
                'verbose_name_plural': 'Типы предметов',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Введите номер пары (1, 2, 3...)', unique=True, verbose_name='Номер пары')),
                ('start_time', models.TimeField(help_text='Введите время начала пары', verbose_name='Время начала')),
                ('end_time', models.TimeField(help_text='Введите время окончания пары', verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Временной слот (пара)',
                'verbose_name_plural': 'Временные слоты (пары)',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.CharField(choices=[('Четные', 'Четные'), ('Нечетные', 'Нечетные'), ('Все', 'Все')], default='Все', help_text='Выберите тип недели', max_length=31, verbose_name='Тип недели')),
                ('week_day', models.ForeignKey(help_text='Выберите день недели', on_delete=django.db.models.deletion.PROTECT, to='studies.day', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название предмета', max_length=255, verbose_name='Название предмета')),
                ('audience', models.ForeignKey(help_text='Выберите аудиторию', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='buildings.audiences', verbose_name='Аудитория')),
                ('groups', models.ManyToManyField(help_text='Выберите учебные группы', related_name='subjects', to='groups.studygroups', verbose_name='Учебные группы')),
                ('schedule', models.ManyToManyField(help_text='Выберите подходящее расписание', to='studies.schedule', verbose_name='Расписание')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
    ]
