# Generated by Django 5.2 on 2025-12-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='teachers',
            field=models.ManyToManyField(help_text='Выберите преподавателей предмета', limit_choices_to={'role': 'TEACHER'}, related_name='teaching_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_type',
            field=models.ForeignKey(help_text='Выберите тип предмета', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='studies.subjectstypes', verbose_name='Тип предмета'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slot',
            field=models.ForeignKey(help_text='Выберите номер пары', on_delete=django.db.models.deletion.PROTECT, to='studies.timeslot', verbose_name='Временной слот (пара)'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('week_day', 'time_slot', 'week_type')},
        ),
    ]
