# Generated by Django 5.2 on 2026-01-13 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('studies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Дата проведения занятия', verbose_name='Дата')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Отметьте, если занятие отменяется', verbose_name='Занятие отменено')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация об изменении', verbose_name='Примечания')),
                ('audience', models.ForeignKey(blank=True, help_text='Оставьте пустым, чтобы использовать аудиторию из основного расписания', null=True, on_delete=django.db.models.deletion.PROTECT, to='buildings.audiences', verbose_name='Аудитория (переопределение)')),
                ('subject', models.ForeignKey(help_text='Выберите предмет', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='studies.subjects', verbose_name='Предмет')),
                ('time_slot', models.ForeignKey(help_text='Выберите номер пары', on_delete=django.db.models.deletion.PROTECT, to='studies.timeslot', verbose_name='Временной слот (пара)')),
            ],
            options={
                'verbose_name': 'Переопределение расписания',
                'verbose_name_plural': 'Переопределения расписания',
                'ordering': ['date', 'time_slot__number'],
                'unique_together': {('subject', 'date', 'time_slot')},
            },
        ),
    ]
