# Generated by Django 5.2 on 2026-01-21 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_scheduleoverride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='schedule',
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_type', models.CharField(choices=[('Четные', 'Четные'), ('Нечетные', 'Нечетные'), ('Все', 'Все')], default='Все', help_text='Выберите тип недели', max_length=31, verbose_name='Тип недели')),
                ('subject', models.ForeignKey(help_text='Выберите предмет', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='studies.subjects', verbose_name='Предмет')),
                ('time_slot', models.ForeignKey(help_text='Выберите номер пары', on_delete=django.db.models.deletion.PROTECT, to='studies.timeslot', verbose_name='Временной слот (пара)')),
                ('week_day', models.ForeignKey(help_text='Выберите день недели', on_delete=django.db.models.deletion.PROTECT, to='studies.day', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Расписание предмета',
                'verbose_name_plural': 'Расписания предметов',
                'ordering': ['week_day', 'time_slot__number'],
                'unique_together': {('subject', 'week_day', 'time_slot', 'week_type')},
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
