# Generated by Django 5.2 on 2026-01-22 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroups_course_studygroups_faculty'),
        ('studies', '0004_remove_subjects_schedule_subjectschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='groups',
            field=models.ManyToManyField(help_text='Выберите учебные группы для этого занятия', related_name='schedules', to='groups.studygroups', verbose_name='Учебные группы'),
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='teachers',
            field=models.ManyToManyField(help_text='Выберите преподавателей для этого занятия', limit_choices_to={'role': 'TEACHER'}, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели'),
        ),
    ]
