# Generated by Django 5.2 on 2026-01-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_remove_subjects_groups_remove_subjects_teachers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleOverride',
        ),
    ]
