# Generated by Django 5.2 on 2026-01-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_remove_schedule_override'),
    ]

    operations = [
    ]
