# Generated by Django 5.2 on 2025-12-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите Наименование учебной группы', max_length=50, verbose_name='Наименование учебной группы')),
                ('description', models.TextField(help_text='Введите описание(дополнительную информацию) об учебной группе', verbose_name='Описание учебной группы')),
                ('is_active', models.BooleanField(default=True, help_text='Действующая группа или нет', verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
            },
        ),
    ]
