# Generated by Django 5.2 on 2025-12-10 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroups',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Выберите студентов группы', limit_choices_to={'role': 'STUDENT'}, related_name='study_groups', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
