# Generated by Django 5.2 on 2026-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroups',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Курс обучения (1-6)', null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='studygroups',
            name='faculty',
            field=models.CharField(blank=True, help_text='Факультет, к которому относится группа', max_length=255, verbose_name='Факультет'),
        ),
    ]
