# Generated by Django 5.2 on 2026-01-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Кафедра преподавателя', max_length=255, verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, help_text='Номер кабинета преподавателя', max_length=50, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Контактный телефон', max_length=20, verbose_name='Телефон'),
        ),
    ]
