# Generated by Django 5.2 on 2025-05-16 19:06

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudiencesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название типа', max_length=63, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип аудитории',
                'verbose_name_plural': 'Типы аудиторий',
            },
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование строения(корпуса)', max_length=255, verbose_name='Строение(Корпус)')),
                ('country', django_countries.fields.CountryField(help_text='Введите страну где находится строение(корпус)', max_length=2, verbose_name='Страна')),
                ('region', models.CharField(blank=True, help_text='Введите регион где находится строение(корпус)', max_length=100, verbose_name='Регион')),
                ('city', models.CharField(help_text='Введите город где находится строение(корпус)', max_length=100, verbose_name='Город')),
                ('street', models.CharField(help_text='Введите улицу где находится строение(корпус)', max_length=255, verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Введите номер строения', max_length=100, verbose_name='Номер строения')),
                ('address', models.TextField(blank=True, help_text='Введите адрес строения', verbose_name='Адрес строения')),
            ],
            options={
                'verbose_name': 'Строение(Корпус)',
                'verbose_name_plural': 'Строении(Корпусы)',
            },
        ),
        migrations.CreateModel(
            name='Audiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Название (если не указано — сформируется автоматически)', max_length=63, verbose_name='Введите название аудитории')),
                ('auditorium_number', models.PositiveSmallIntegerField(help_text='Введите номер аудитории', verbose_name='Номер аудитории')),
                ('floor_number', models.PositiveSmallIntegerField(help_text='Введите этаж на котором находиться аудитория', verbose_name='Этаж')),
                ('auditorium_type', models.ForeignKey(help_text='Выберите тип аудитории', max_length=50, on_delete=django.db.models.deletion.PROTECT, related_name='audience', to='buildings.audiencestypes', verbose_name='Тип аудитории')),
                ('building', models.ForeignKey(help_text='Выберите строение(корпус) в котором находится аудитория', on_delete=django.db.models.deletion.PROTECT, related_name='audiences', to='buildings.buildings', verbose_name='Строение(Корпус)')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
            },
        ),
    ]
