name: CI/CD

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CI/CD deploy on google cloud VM instance
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_port }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 30m
          script: |
            cd ${{ secrets.PATH }};
            git pull origin master;
            docker compose down;
            docker compose up --build -d;
            docker compose restart nginx;
